/**
 * Site Export — download generated sites as ZIP files.
 *
 * Users can /export to get their site as a ZIP file sent in Telegram.
 * The ZIP contains all site files (HTML, CSS, JS) ready for any hosting.
 * No lock-in: take your code anywhere.
 */

import { log } from "@wai/core";
import { writeFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execSync } from "node:child_process";

/** Export result. */
export interface ExportResult {
  success: boolean;
  filePath?: string;
  fileName?: string;
  fileSize?: number;
  error?: string;
}

/**
 * Export a site's HTML as a ZIP file.
 * Returns the path to the generated ZIP file.
 */
export async function exportSiteAsZip(
  slug: string,
  html: string,
  description: string,
): Promise<ExportResult> {
  log.info({ service: "export", action: "creating-zip", slug, htmlSize: html.length });

  const tempDir = await mkdtemp(join(tmpdir(), "wai-export-"));

  try {
    // Create site directory structure
    const siteDir = join(tempDir, slug);
    await writeFile(join(tempDir, "index.html"), html);

    // Create a README
    const readme = generateReadme(slug, description);
    await writeFile(join(tempDir, "README.md"), readme);

    // Create the ZIP
    const zipFileName = `${slug}.zip`;
    const zipPath = join(tmpdir(), zipFileName);

    // Use system zip command
    execSync(`cd "${tempDir}" && zip -r "${zipPath}" . -x "*.DS_Store"`, {
      timeout: 10000,
    });

    // Get file size
    const { statSync } = await import("node:fs");
    const stats = statSync(zipPath);

    log.info({ service: "export", action: "zip-created", slug, size: stats.size, path: zipPath });

    // Clean up temp dir (keep zip)
    await rm(tempDir, { recursive: true, force: true }).catch(() => {});

    return {
      success: true,
      filePath: zipPath,
      fileName: zipFileName,
      fileSize: stats.size,
    };
  } catch (error) {
    log.error({ service: "export", action: "zip-failed", slug, error: String(error) });
    await rm(tempDir, { recursive: true, force: true }).catch(() => {});
    return { success: false, error: String(error) };
  }
}

/**
 * Generate a README.md for the exported site.
 */
export function generateReadme(slug: string, description: string): string {
  return `# ${slug}

> Generated by [Wai](https://wai.computer) — AI site builder in Telegram

## Description

${description}

## How to use

1. Open \`index.html\` in your browser
2. Or deploy to any static hosting:
   - **Netlify**: drag & drop the folder
   - **Vercel**: \`npx vercel\`
   - **GitHub Pages**: push to repo → Settings → Pages
   - **Cloudflare Pages**: connect repo or drag & drop

## Tech Stack

- [Tailwind CSS](https://tailwindcss.com) (via CDN)
- [Alpine.js](https://alpinejs.dev) (interactivity)
- [Lucide Icons](https://lucide.dev)
- [Google Fonts](https://fonts.google.com)

## Live URL

https://${slug}.wai.computer

---

Made with Wai ✨ — [@waicomputer_bot](https://t.me/waicomputer_bot)
`;
}

/**
 * Format file size in human-readable format.
 */
export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/**
 * Clean up an exported ZIP file after sending.
 */
export async function cleanupExport(filePath: string) {
  try {
    const { unlink } = await import("node:fs/promises");
    await unlink(filePath);
    log.debug({ service: "export", action: "cleanup", path: filePath });
  } catch {
    // Ignore cleanup errors
  }
}
